[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true

[theme]
base = "light"
primaryColor = "#6b6b6b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f3f3"
textColor = "#111111"
font = "monospace"
