[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true

[theme]
base = "dark"
primaryColor = "#949494"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0c0c0c"
textColor = "#eeeeee"
font = "monospace"
